config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/auth/spotify/callback', to: 'users#spotify'
  get '/users/:id', to: 'users#show', as: 'user_profile'
  post '/followings', to: 'followings#create', as: 'followings'
  delete 'followings/:id', to: 'followings#destroy', as: 'following'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'update_user'
  patch 'users/:id', to: 'users#update'

  root to: "pages#home"

  get '/search', to: 'pages#search', as: 'search'
  resources :artists, only: :show do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :reviews, except: [:create, :destroy] do
    resources :likes, only: [:create]
  end

  resources :albums, only: :show  do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :tracks, only: :show  do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:destroy]
  resources :likes, only: [:destroy]


  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  get '*path', to: 'application#not_found'
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def show
    @review = Review.new
    @reviews = Review.where(spotify_item_id: params[:id])
    @artist = RSpotify::Artist.find(params[:id])
    @albums = @artist.albums
    session[:selected_artist_id] = @artist.id
  rescue RestClient::BadRequest
    render file: "#{Rails.root}/public/404.html", layout: 'application', status: :not_found
  end
end

app/views/artists/show.html.erb
<div class="total-artist-margin">
  <div class="d-flex align-items margin-left-title">
    <h1><%= @artist.name %></h1>

  </div>

  <div data-controller="review-form">
    <div class="artist-content">
      <div class="artist-image-favorites">
        <% if @artist.images.any? %>
          <%= image_tag @artist.images.first["url"], class: "artist-image" %>
        <% end %>
        <div class="d-flex align-items-center margin-button">
          <div class="favorite-button">
            <% if Favorite.find_by(user: current_user, spotify_item_id: @artist.id).present? %>
              <%= link_to 'Remove from Favorites', favorite_path(Favorite.find_by(user: current_user, spotify_item_id: @artist.id)), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-warning' %>
            <% else %>
              <%=button_to 'Add as favorite', artist_favorites_path(@artist.id), method: :post, class: 'btn btn-primary favorite' %>
            <% end %>
          </div>
          <div>
            <button class='btn btn-primary' data-action="click->review-form#displayForm" id='open-review-form'>Leave a review</button>
          </div>
        </div>
      </div>

      <div class="artist-info">
        <div class="artist-tracks-albums">
          <div class="most-popular-tracks">
            <h2>Most Popular Tracks (Worldwide):</h2>
            <ul class="margin-popular-tracks">
              <% @artist.top_tracks(:US).first(5).each do |track| %>
                <li><%= track.name %></li>
              <% end %>
            </ul>
          </div>

          <div class="artist-albums">
            <h2 class="album-title-margin">Albums:</h2>
            <div class="albums-container-unique">
              <% half_size = (@artist.albums.size / 2.0).ceil %>
              <ol class="album-list">
                <% @artist.albums.first(half_size).each do |album| %>
                  <li><%= link_to album.name, album_path(album.id) %></li>
                <% end %>
              </ol>
              <ol class="album-list" start="<%= half_size + 1 %>">
                <% @artist.albums.last(@artist.albums.size - half_size).each do |album| %>
                  <li><%= link_to album.name, album_path(album.id) %></li>
                <% end %>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="review-form-container" class="mt-3" data-review-form-target="form">
      <%= render 'reviews/form', review: @review, type: "artist" %>
    </div>
  </div>

  <div class="artist-review_section">
    <h2>Reviews</h2>
    <ul class="list-unstyled">
      <% Review.where(spotify_item_id: params[:id], spotify_item_type: "artist").each do |review| %>
        <div class="review-box">
          <div class="review-content">
            <div class="d-flex">
              <div class="review-header mb-2">
                <%= image_tag "#{review.user.avatar}", class: "avatar dropdown-toggle profile-image mr-3", alt:"profile image"%>
                <div class="row mr-4 user-info">
                  <strong class="mr-4" style="color: black"><%= review.user.name %></strong>
                  <span class="review-info text-muted mr-4">
                    <%= Following.where(followed_user_id: review.user).count %> followers - <%= review.user.reviews.count %> reviews
                  </span>
                </div>
              </div>

              <div class="d-flex align-items-center like-margin ms-auto">
                <% liked_review = Like.find_by(user: current_user, review_id: review.id) %>
                <% if liked_review %>
                  <%= link_to 'Unlike', like_path(Like.find_by(user: current_user, review_id: review.id)),
                  data: {turbo_method: :delete},
                  class: 'btn btn-warning btn-sm me-2' %>
                <% else %>
                  <%= simple_form_for Like.new, url: review_likes_path(review_id: review.id), method: :post do |f| %>
                    <%= f.hidden_field :review_id, value: review.id %>
                    <%= f.submit "Like", class: 'btn btn-primary btn-sm me-2' %>
                  <% end %>
                <% end %>
                <span><%= review.likes_count %> likes</span>
              </div>
            </div>
            <p class="review-text"><%= review.content %> <i>(<%= review.rating %>/10)</i></p>
            <div class="review-footer">
              <span class="text-muted"><%= review.created_at.strftime("%d %B %Y") %></span>
            </div>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</div>

<script>
  document.addEventListener('turbo:load', function() {
    const openButton = document.getElementById('open-review-form');
    const formContainer = document.getElementById('review-form-container');
    openButton.addEventListener('click', function(event) {
      event.preventDefault();
      formContainer.classList.toggle('d-none');
    });
  });

  document.addEventListener('DOMContentLoaded', function() {
    const openButton = document.getElementById('open-review-form');
    const formContainer = document.getElementById('review-form-container');
    openButton.addEventListener('click', function(event) {
      event.preventDefault();
      formContainer.classList.toggle('d-none');
    });
  });


</script>