config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/auth/spotify/callback', to: 'users#spotify'
  get '/users/:id', to: 'users#show', as: 'user_profile'
  post '/followings', to: 'followings#create', as: 'followings'
  delete 'followings/:id', to: 'followings#destroy', as: 'following'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'update_user'
  patch 'users/:id', to: 'users#update'

  root to: "pages#home"

  get '/search', to: 'pages#search', as: 'search'
  resources :artists, only: :show do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :reviews, except: [:create, :destroy] do
    resources :likes, only: [:create]
  end

  resources :albums, only: :show  do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :tracks, only: :show  do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:destroy]
  resources :likes, only: [:destroy]


  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  get '*path', to: 'application#not_found'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :likes
  has_many :like_reviews, through: :likes, source: :review

  has_many :favorites
  has_many :favorite_albums, through: :favorites, source: :album
  serialize :avatars, JSON

  has_many :followings, foreign_key: :follower_id

  has_many :followed_relationships, foreign_key: :follower_id, class_name: 'Following'
  has_many :followeds, through: :followed_relationships, source: :followed

  has_many :follower_relationships, foreign_key: :followed_id, class_name: 'Following'
  has_many :followers, through: :follower_relationships, source: :follower

  def following?(other_user)
    followed_relationships.exists?(followed_user_id: other_user.id)
  end

  def follow(other_user)
    followed_relationships.create(followed_user_id: other_user.id)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
require 'rspotify'

class UsersController < ApplicationController
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_CLIENT_SECRET'])

  def index
    @users = User.all
  end

  def spotify
    @user = User.new
    @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    @user.spotify_id = @spotify_user.uri
    if User.find_by(spotify_id: @spotify_user.uri).nil?
      @user.name = @spotify_user.display_name
      @user.password = "kluster"
      @user.email = @spotify_user.email
      @user.birthdate = @spotify_user.birthdate
      @user.country = @spotify_user.country
      @user.avatar = @spotify_user.images.first.url
      @user.save
      sign_in @user
      sign_in @user, :bypass => true
      redirect_to root_path
    else
      @user = User.find_by(spotify_id: @spotify_user.uri)
      sign_in @user
      sign_in @user, :bypass => true
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  rescue ActiveRecord::RecordNotFound
    # User not found, redirect to 404 page
    render file: "#{Rails.root}/public/404.html", layout: 'application', status: :not_found
  end

  def profile
    @user = current_user
    @reviews = @user.reviews
  end

  def update_avatar
    user = current_user
    avatars = fetch_avatars_from_spotify_api(user.spotify_id) # This is hypothetical, you should implement this method to fetch avatars from the Spotify API
    user.avatar = avatars.map(&:to_json)
    user.save
    redirect_to root_path
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_path, alert: "You are not authorized to edit this profile."
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_profile_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def follow(user)
    followed << user unless self == user || followed.include?(user)
  end

  def unfollow(user)
    followed.delete(user)
  end

  def following?(user)
    followed.include?(user)
  end
end


private


def user_params
  params.require(:user).permit(:name, :email, :birthdate, :country, :avatar)
end

app/views/users/_suggested_users.html.erb
<div class="suggested">
<div class="card">
<h1>Suggested Users to Follow</h1>
<div class="container">
  <div class="user-container">


<ul>
  <% User.all.each do |user| %>
    <li>
      <%= image_tag user.avatar || 'default_user_icon.jpg' %>
      <%= link_to user.name, user_profile_path(user.id) %> <br>
      <%= button_to 'Follow', followings_path(followed_user_id: user.id), method: :post %>
    </li>
  <% end %>
</ul>
 </div>
</div>
</div>
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<div class="container w-25">
  <%= simple_form_for @user, url: update_user_path(@user), method: :patch do |f| %>
    <%= f.input :name, input_html: {style: 'border: 3px solid #f8a3fcd1; border-radius: 10px;'}  %>
    <%= f.input :email, input_html: {style: 'border: 3px solid #f8a3fcd1; border-radius: 10px;'}  %>
    <%= f.input :birthdate, input_html: {style: 'border: 3px solid #f8a3fcd1; border-radius: 10px;'}  %>
    <%= f.input :password, label: "New Password", required: false, placeholder: "Change password here", input_html: {style: 'border: 3px solid #f8a3fcd1; border-radius: 10px;'}  %>
    <%= f.input :password_confirmation, label: "Confirm New Password", required: false, input_html: {style: 'border: 3px solid #f8a3fcd1; border-radius: 10px;'}  %>

    <%= f.button :submit, 'Update', class: 'button-purple' %>
  <% end %>
</div>

app/views/users/profile.html.erb
<h1>Profile</h1>
<p>Email: <%= @user.email %></p>

<h2>Reviews</h2>
<% if @reviews.any? %>
  <ul>
    <% @reviews.each do |review| %>
      <li><%= review.content %></li>
    <% end %>
  </ul>
<% else %>
  <p>No reviews yet.</p>
<% end %>

<h2>Avatar</h2>
<% if @avatar_url.present? %>
  <%= image_tag @avatar_url, alt: 'Avatar' %>
<% else %>
  <p>No avatar available.</p>
<% end %>

app/views/users/show.html.erb
<div class="content">
  <div class="profile-info">
    <div class="profile-avatar">
      <% if @user.avatar.present? %>
        <%= image_tag @user.avatar, alt: "User Avatar" %>
      <% else %>
        <%= image_tag 'default_user_icon.jpg', class: 'user-avatar' %>
      <% end %>
    </div>

    <div class="profile-numbers">
      <h2><%= @user.name %></h2>

      <div class="container">
        <% followed_count = Following.where(followed_user_id: @user.id).count %>
        <% if followed_count == 1 %>
          <p><%= followed_count %> Follower</p>
        <% elsif followed_count == 0 %>
          <p>0 Followers</p>
        <% else %>
          <p><%= followed_count %> Followers</p>
        <% end %>
        <% if current_user == @user %>
          <%= link_to 'Edit', edit_user_path(@user), class: 'btn' %>
        <% end %>
      </div>

      <div class="container-button">
        <% unless current_user == @user %>
          <% followed_relationship = Following.find_by(followed_user_id: @user.id, follower_id: current_user.id) %>
          <% if followed_relationship %>
            <%= button_to 'Unfollow', following_path(followed_relationship), method: :delete %>
          <% else %>
            <%= button_to 'Follow', followings_path(followed_user_id: @user.id), method: :post %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="favorite-container">
    <div class="favorite-album">
      <div class="fav-title">
        <h4> Favorite Albums and Artists </h4>
      </div>
      <% if @user.favorites.any? %>
        <div class="fav-card">
          <%= render "shared/fav_card" %>
        </div>
      <% else %>
        <h5>No favorites to display.</h5>
      <% end %>
    </div>
  </div>

  <div class="container-review">
    <h2><%= @user.name %>'s reviews</h2>
    <% if @reviews.nil? %>
      <h3>No reviews to display.</h3>
      <% else %>
        <div class="review-feed col-10">
          <%= render 'reviews/review_card' %>
        </div>
        <% end %>
  </div>
</div>