config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/auth/spotify/callback', to: 'users#spotify'
  get '/users/:id', to: 'users#show', as: 'user_profile'
  post '/followings', to: 'followings#create', as: 'followings'
  delete 'followings/:id', to: 'followings#destroy', as: 'following'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'update_user'
  patch 'users/:id', to: 'users#update'

  root to: "pages#home"

  get '/search', to: 'pages#search', as: 'search'
  resources :artists, only: :show do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :reviews, except: [:create, :destroy] do
    resources :likes, only: [:create]
  end

  resources :albums, only: :show  do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :tracks, only: :show  do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:destroy]
  resources :likes, only: [:destroy]


  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  get '*path', to: 'application#not_found'
end

app/views/shared/_fav_card.html.erb
<% @user.favorites.each do |favorite| %>
  <div class="favorite-card">
    <div class="image">
      <% if favorite.spotify_item_id == 'album' %>
      <%= link_to  album_path(favorite.spotify_item_id) do %>
        <%= image_tag favorite.image %>
        <% end %>
        <% else favorite.spotify_item_id == 'artist'%>
        <%= link_to  artist_path(favorite.spotify_item_id) do %>
        <%= image_tag favorite.image %>
        <% end %>
      <% end %>
    </div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <div class="touch-container">
    <h4>Get in touch</h4>
    <p>kluster.team@contact.com</p>
    </div>
    <div class="connect-container">
    <h4>Connect</h4>
    <p>maximiliamrojas@gmail.com</p>
    <p>giulioavalos@gmail.com</p>
    <p>gregoirecazier@gmail.com</p>
    </div>
    <div class="location-container">
    <h4>Location</h4>
    <p>Huerta Coworking</p>
    <p>Humboldt 1967, C1414 </p>
    <p>Palermo, Buenos Aires</p>
    </div>
  </div>
      <div class="footer-copyright">
    <h5>This footer is made with    <i class="fas fa-heart"></i>    by Kluster Team</h5>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-kluster bg-transparent">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://media.istockphoto.com/id/1303141949/photo/white-blank-vinyl-record-disc-label-sticker-template-mock-up-isolated-on-black.jpg?s=612x612&w=0&k=20&c=7JRG_w1joTZPkv_Y-1nx5aVPgLQAPF6sC0gbsJDlsAQ=" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <div class="navbar-item">
        <%= form_tag(search_path, method: :get, class: "navbar-form") do %>
          <div class="field has-addons">
            <div class="control">
              <%= text_field_tag :query, params[:query], placeholder: "Search...", class: "input", id: "searchInput", style: 'border: 3px solid #f8a3fcd1; border-radius: 20px; padding: 6px;' %>
              <%= button_tag "Search", class: "button-purple button", id: "searchButton" %>
            </div>
          </div>
        <% end %>
      </div>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <div class="navbar-brand">
              <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
              <%= image_tag 'default_user_icon.jpg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", user_profile_path(current_user.id), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
            </div>
        <% else %>
          <!--li class="nav-item"-->
          <button class="button-purple button">
            <%= link_to 'Sign in with Spotify', '/auth/spotify', method: :post %>
          </button>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>