config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/auth/spotify/callback', to: 'users#spotify'
  get '/users/:id', to: 'users#show', as: 'user_profile'
  post '/followings', to: 'followings#create', as: 'followings'
  delete 'followings/:id', to: 'followings#destroy', as: 'following'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'update_user'
  patch 'users/:id', to: 'users#update'

  root to: "pages#home"

  get '/search', to: 'pages#search', as: 'search'
  resources :artists, only: :show do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :reviews, except: [:create, :destroy] do
    resources :likes, only: [:create]
  end

  resources :albums, only: :show  do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :tracks, only: :show  do
    resources :reviews, only: [:create]
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:destroy]
  resources :likes, only: [:destroy]


  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  get '*path', to: 'application#not_found'
end

app/models/album.rb
class Album < ApplicationRecord

end

app/controllers/albums_controller.rb
# app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_artist
  before_action :set_album
  before_action :authenticate_spotify

  def index
    @albums = @artist.albums
  end

  def show
    @album = RSpotify::Album.find(params[:id])
    @tracks = @album.tracks
    @review = Review.new
    @reviews = Review.where(spotify_item_id: @album.id)
  end

  private

  def set_artist
    @artist = RSpotify::Artist.find(session[:selected_artist_id])
  end

  def set_album
    session[:selected_album_id] = params[:id]
  end

  def authenticate_spotify
    RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_CLIENT_SECRET'])
  end
end

app/views/albums/index.html.erb
<h2>Albums:</h2>
<ul>
  <% @artist.albums.each do |album| %>
    <li><%= link_to album.name, artist_album_path(@artist.id, album.id) %></li>
  <% end %>
</ul>

app/views/albums/show.html.erb
<div class="total-album-margin">
  <% if @album %>
    <div class="align-items-center">
  <h1><%= @album.name %> <i>by</i> <%= @artist.name %></h1>

      <div class="mt-auto">
        <div class="d-flex align-items-center margin-button">
          <% if Favorite.find_by(user: current_user, spotify_item_id: @album.id).present? %>
            <%= link_to 'Remove from Favorites', favorite_path(Favorite.find_by(user: current_user, spotify_item_id: @album.id)), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-warning me-2' %>
          <% else %>
            <%=button_to 'Add as favorite', album_favorites_path(@album.id), method: :post, class: 'btn btn-primary favorite' %>
          <% end %>
    <button class='btn btn-primary' data-action="click->review-form#displayForm" id='open-review-form-album'>Leave a review</button>


        </div>
        <div class="col-md-8 d-flex flex-column align-items-center">
          <div class="d-flex">
            <div class="row align-items-start col-6 image-margin">
              <div>
                <% if @album.images.any? %>
                  <%= image_tag @album.images.first["url"], class: "album-image img-fluid mb-3" %>
                <% end %>
              </div>
            </div>
            <div class="col-md-8 tracks-margin">
              <div class="row">
                <h2 class="margin-tracks-album">Tracks</h2>
                <div class="col margin-top-tracks">
                  <ol>
                    <% @tracks.first(@tracks.size / 2).each do |track| %>
                      <li><%= track.name %></li>
                    <% end %>
                  </ol>
                </div>
                <div class="col">
                  <ol start="<%= @tracks.size / 2 + 1 %>">
                    <% @tracks.last(@tracks.size / 2).each do |track| %>
                      <li><%= track.name %></li>
                    <% end %>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

  <div id="review-form-container-album" class=" mt-3 d-none" data-review-form-target="form">
            <%= render 'reviews/form', review: @review, type: "album" %>
          </div>
      <div class="review_section">
        <h2>Reviews</h2>

        <ul class="list-unstyled">
          <% Review.where(spotify_item_id: params[:id], spotify_item_type: "album").each do |review| %>
            <div class="review-box">
              <div class="review-content">
                <div class="d-flex">
                  <div class="review-header mb-2">
                    <%= image_tag "#{review.user.avatar}", class: "avatar dropdown-toggle profile-image mr-3", alt:"profile image"%>
                    <div class="row mr-4 user-info">
                      <strong class="mr-4" style="color: black"><%= review.user.name %></strong>
                      <span class="review-info text-muted mr-4">
                        <%= Following.where(followed_user_id: review.user).count %> followers - <%= review.user.reviews.count %> reviews
                      </span>
                    </div>
                  </div>

              <div class="d-flex align-items-center like-margin">
                <% liked_review = Like.find_by(user: current_user, review_id: review.id) %>
                <% if liked_review %>
                  <%= link_to 'Unlike', like_path(Like.find_by(user: current_user, review_id: review.id)),
                  data: {turbo_method: :delete},
                  class: 'btn btn-warning btn-sm me-2' %>
                <% else %>
                  <%= simple_form_for Like.new, url: review_likes_path(review_id: review.id), method: :post do |f| %>
                    <%= f.hidden_field :review_id, value: review.id %>
                    <%= f.submit "Like", class: 'btn btn-primary btn-sm me-2' %>
                  <% end %>
                <% end %>
                <span><%= review.likes_count %> likes</span>
              </div>

                </div>
                <p class="review-text"><%= review.content %> <i>(<%= review.rating %>/10)</i></p>
                <div class="review-footer">
                  <span class="text-muted"><%= review.created_at.strftime("%d %B %Y") %></span>
                </div>
              </div>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
  <% else %>
    <p>Album not found.</p>
  <% end %>

</div>

<script>
  document.addEventListener('turbo:load', function() {
    const openButton = document.getElementById('open-review-form-album');
    const formContainer = document.getElementById('review-form-container-album');
    openButton.addEventListener('click', function(event) {
      event.preventDefault();
      formContainer.classList.toggle('d-none');
    });
  });

  document.addEventListener('DOMContentLoaded', function() {
    const openButton = document.getElementById('open-review-form');
    const formContainer = document.getElementById('review-form-container');
    openButton.addEventListener('click', function(event) {
      event.preventDefault();
      formContainer.classList.toggle('d-none');
    });
  });
</script>